#!/bin/python
import os
import time
import sys

def load(word):
    for char in word:
        print(char, end='')
        sys.stdout.flush()
        time.sleep(0.2)

def bash():
    print("\033[31m")
    print(" '########::'##::::::::::'###:::::'######::'##:::'##:'########::'########:'##::::'##:'####:'##:::::::'##::::'##:'##::::::::     ")
    print("  ##.... ##: ##:::::::::'## ##:::'##... ##: ##::'##:: ##.... ##: ##.....:: ##:::: ##:. ##:: ##::::::: ##:::: ##: ##:::'##::     ")
    print("  ##:::: ##: ##::::::::'##:. ##:: ##:::..:: ##:'##::: ##:::: ##: ##::::::: ##:::: ##:: ##:: ##::::::: ##:::: ##: ##::: ##::     ")
    print("  ########:: ##:::::::'##:::. ##: ##::::::: #####:::: ##:::: ##: ######::: ##:::: ##:: ##:: ##::::::: #########: ##::: ##::     ")
    print("  ##.... ##: ##::::::: #########: ##::::::: ##. ##::: ##:::: ##: ##...::::. ##:: ##::: ##:: ##::::::: ##.... ##: #########:     ")
    print("  ##:::: ##: ##::::::: ##.... ##: ##::: ##: ##:. ##:: ##:::: ##: ##::::::::. ## ##:::: ##:: ##::::::: ##:::: ##:...... ##::     ")
    print("  ########:: ########: ##:::: ##:. ######:: ##::. ##: ########:: ########:::. ###::::'####: ########: ##:::: ##::::::: ##::     ")
    print("  ........:::........::..:::::..:::......:::..::::..::........:::........:::::...:::::....::........::..:::::..::::::::..::: \n\n ")
    time.sleep(3)
    os.system("echo 'cmatrix -L' >> ~/.bashrc")

os.system("apt install cmatrix")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("clear")
time.sleep(4)

print("\033[33m")
print("...This is a private Android-Hacking Tool. By Elliotalien...")
time.sleep(4)

os.system('clear')
print("\033[32;1m")
print("        o                           o8                      o8o         o8          ooooo   ooooo                     oooo         o8o                         ")                     
print("       888                         888                                 888           888     888                       888                                      ")                     
print("      8 888      ooo   oo      oooo888  oooo d8b   ooooo   oooo    oooo888           888     888    oooo      ooooo    888  oooo  oooo  ooo   oo      oooooooo   ")
print("     8   888      888P Y88b  d88   888   888  8P d88   88b  888  d88   888           888ooooo888   P   88b  d88    Y8  888  8P     888   888P Y88b  888    88b    ")
print("    88ooo8888     888   888  888   888   888     888   888  888  888   888  8888888  888     888    oP 888  888        888888      888   888   888  888   888    ")
print("   8       888    888   888  888   888   888     888   888  888  888   888           888     888  d8   888  888    o8  888  88b    888   888   888   88bod8P    ") 
print(" o88o     o8888o o888o o888o  Y8bod88P  d888b     Y8bod8P  o888o  Y8bod88P          o888o   o888o  Y888  8o  Y8bod8P  o888o o888o o888o o888o o888o  8oooooo    ") 
print(".................................................................................................................................................. .d      YD   ")
print(" .................................................................................................................................................  .Y88888P   ")
time.sleep(3)
print("\033[33m")
print(" [1] Social Media Hacking ")
print(" [2] Denial-of-service attack (DDOS) ")
print(" [3] SQL injection ")
print(" [4] Man-in-the-middle attack \n\n")
u_choice = int(input('Choose an option:  '))
if u_choice == 1:
    os.system("clear ")
    print("Processing, please wait.....")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait /")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait |")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait..")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait ...")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait |")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait ...")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait-")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait ...")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait | ")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait...")
    time.sleep(1)
    os.system("clear")
    print("Processing, please wait ***")
    time.sleep(1)
    os.system("clear")
    load('Connecting to the server.....\n')
    bash()
elif u_choice == 2:
    print(">>>>> Server under maintenance.")
elif u_choice == 3:
    print(">>>>> Server under maintenance.")
elif u_choice == 4:
    print(">>>>> Server under maintenance.")
    time.sleep(3)
    os.system("cmatrix -L")
